#!/usr/bin/env node
// build.mjs — scans images/ folder and rewrites data.js
// Usage: node build.mjs
// Node 18+, zero dependencies

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dir = path.dirname(fileURLToPath(import.meta.url));
const IMAGES_DIR = path.join(__dir, 'images');
const DATA_FILE  = path.join(__dir, 'data.js');

const EXTS = new Set(['.jpg', '.jpeg', '.png', '.gif', '.webp', '.avif', '.svg']);

if (!fs.existsSync(IMAGES_DIR)) {
  fs.mkdirSync(IMAGES_DIR);
  console.log('Created images/ folder — drop your photos there and re-run.');
  process.exit(0);
}

const files = fs.readdirSync(IMAGES_DIR)
  .filter(f => EXTS.has(path.extname(f).toLowerCase()))
  .sort();

if (files.length === 0) {
  console.warn('No images found in images/. Add .jpg/.png/.svg files and re-run.');
  process.exit(0);
}

const entries = files.map(f => `  { src: 'images/${f}' }`).join(',\n');
const output = `// Auto-generated by build.mjs — do not edit manually
// Run: node build.mjs  to regenerate from the images/ folder
window.IMAGES = [\n${entries},\n];\n`;

fs.writeFileSync(DATA_FILE, output);
console.log(`data.js updated — ${files.length} image(s) indexed.`);
