// Auto-generated by build.mjs — do not edit manually
// Run: node build.mjs  to regenerate from the images/ folder
window.IMAGES = [
  { src: 'images/photo-01.svg' },
  { src: 'images/photo-02.svg' },
  { src: 'images/photo-03.svg' },
  { src: 'images/photo-04.svg' },
  { src: 'images/photo-05.svg' },
  { src: 'images/photo-06.svg' },
  { src: 'images/photo-07.svg' },
  { src: 'images/photo-08.svg' },
  { src: 'images/photo-09.svg' },
  { src: 'images/photo-10.svg' },
  { src: 'images/photo-11.svg' },
  { src: 'images/photo-12.svg' },
  { src: 'images/photo-13.svg' },
  { src: 'images/photo-14.svg' },
  { src: 'images/photo-15.svg' },
  { src: 'images/photo-16.svg' },
  { src: 'images/photo-17.svg' },
  { src: 'images/photo-18.svg' },
  { src: 'images/photo-19.svg' },
  { src: 'images/photo-20.svg' },
];
